services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud
    restart: always
    ports:
      - "8080:8080"
    environment:
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_HOST: mariadb
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: supersecret
      OWNCLOUD_ADMIN_USERNAME: admin
      OWNCLOUD_ADMIN_PASSWORD: adminpassword
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: redis
      OWNCLOUD_REDIS_PASSWORD: redispassword
      OWNCLOUD_LDAP_ENABLED: "true"
      OWNCLOUD_LDAP_HOST: openldap
      OWNCLOUD_LDAP_PORT: 389
      OWNCLOUD_LDAP_BASE_DN: dc=example,dc=org
      OWNCLOUD_LDAP_USER_FILTER: "(objectClass=inetOrgPerson)"
      OWNCLOUD_LDAP_GROUP_FILTER: "(objectClass=groupOfNames)"
    depends_on:
      - mariadb
      - redis
      - openldap
    volumes:
      - ./data/owncloud:/mnt/data
    networks:
      - internal_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: supersecret
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - internal_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - internal_net

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: always
    environment:
      LDAP_ORGANISATION: "MiEmpresa"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/slapd/config:/etc/ldap/slapd.d
      - ./data/slapd/database:/var/lib/ldap
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge